services:
  grafana:
    user: root
    container_name: 'grafana-resourcesexporter-app'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-11.0.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-resourcesexporter-app
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/grafana-resourcesexporter-app

    environment:
      DEVELOPMENT: "true"
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.grafana-resourcesexporter-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-resourcesexporter-app
      GF_AUTH_ANONYMOUS_ENABLED: "false"
